# Generated by Django 2.2.10 on 2020-02-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Catogary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Catogary'),
            preserve_default=False,
        ),
    ]
