# Generated by Django 2.2.10 on 2020-03-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_catogary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Catogary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Catogary'),
        ),
    ]
