# Generated by Django 2.2.10 on 2020-05-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200503_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='I love to write blogs......', max_length=500),
        ),
    ]
